export const ERROR_CODE = {
  NET_E_TOO_MANY_REQUESTS: 429,
  NET_E_CONTENT_FILTER_UNSAFE: 400,
  NET_E_SERVICE_UNAVAILABLE: 503,
  NET_E_GATEWAY_TIMEOUT: 504,
  NET_E_BAD_REQUEST: 400,
  NET_E_UNAUTHORIZED: 401,
};
